In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
area = [1.9,2.4,5.3,3.6,2.5,4.2,5.2,6.3,1.2,3.6,4.3,4.1,6.2,3.8,4.5]
price= [210,250,480,390,220,460,490,580,180,350,410,450,580,450,425]

In [5]:
x = np.array(area)
y = np.array(price)
m = 2.5
c = 10.9
LR = 0.003

for i in range(500):
    # get predictions
    yhat = m*x + c
    
    # calculate error
    error = np.mean((y-yhat)**2)
    
    # Gradient descent to update/change the values of m and c
    dedm = 2*np.dot((yhat-y),x)
    m = m - LR*dedm
    
    dedc = 2*np.dot((yhat-y),np.ones(y.size))
    c = c - LR*dedc
    
    print(error)
    

154562.98583333334
68578.39751202296
30763.608373668376
14132.355504460773
6816.961072615327
3598.4072841838965
2181.5399318181658
1557.0245476365724
1280.9882089556454
1158.2295273424495
1102.9047462704411
1077.2620359023383
1064.6988363281698
1057.9133567071824
1053.693991284494
1050.6278744939493
1048.0931781115137
1045.8159562463377
1043.6752600397533
1041.6174332785836
1039.6184222132256
1037.6672004589366
1035.7584796249416
1033.8895035071118
1032.0586381021562
1030.2647513690124
1028.5069402987187
1026.784410722628
1025.0964242932703
1023.4422750088227
1021.8212787330745
1020.2327684335406
1018.6760919372755
1017.1506107969085
1015.6556996478637
1014.1907457844761
1012.7551488351892
1011.3483204841217
1009.9696842157156
1008.6186750722195
1007.2947394194193
1005.9973347185448
1004.7259293034151
1003.4800021623245
1002.2590427244406
1001.0625506505244
999.8900356278812
998.7410171694208
997.615024416757
996.5115959472536
995.4302795849309
994.3706322151702
993.3322196031314
992.3

In [6]:
print(m,c)

83.52332375815439 65.89314629671057


# linear regression with sklearn

In [11]:
x = np.array(area).reshape(15,1)
y = np.array(price)

In [12]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [13]:
# train the model and get optimized model to make predictions
model.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [14]:
print(model.coef_,model.intercept_)

[83.47304617] 66.11619809130752


In [15]:
# makeing prediction for area = 2600 sq ft
model.predict([[2.6]])

array([283.14611813])

In [25]:
x = np.array(area)
x

array([1.9, 2.4, 5.3, 3.6, 2.5, 4.2, 5.2, 6.3, 1.2, 3.6, 4.3, 4.1, 6.2,
       3.8, 4.5])

In [26]:
x.shape

(15,)

In [27]:
x.reshape(15,1)

array([[1.9],
       [2.4],
       [5.3],
       [3.6],
       [2.5],
       [4.2],
       [5.2],
       [6.3],
       [1.2],
       [3.6],
       [4.3],
       [4.1],
       [6.2],
       [3.8],
       [4.5]])