# Numpy

In [1]:
import numpy as np

In [98]:
x = np.array([7,4,5,2,6])
print(x)

[7 4 5 2 6]


In [99]:
type(x)

numpy.ndarray

In [100]:
x

array([7, 4, 5, 2, 6])

In [101]:
x.dtype

dtype('int32')

In [102]:
x = np.array([7,4,5,2.2,6])
print(x)

[7.  4.  5.  2.2 6. ]


In [103]:
x.dtype

dtype('float64')

In [104]:
a = [4,2,3]
b = [7,5,6]
print(a+b)

[4, 2, 3, 7, 5, 6]


In [105]:
a = np.array([4,2,3])
b = np.array([7,5,6])
print(a+b)

[11  7  9]


In [106]:
x = np.array([7,4,5,8,6,2])
x.ndim

1

In [107]:
x.shape

(6,)

In [110]:
x = np.array([[7,1,2],[3,4,7],[6,5,4]])
x

array([[7, 1, 2],
       [3, 4, 7],
       [6, 5, 4]])

In [109]:
x.shape

(3, 3)

In [111]:
x.ndim

2

In [112]:
print(x.min())
print(x.max())
print(x.mean())

1
7
4.333333333333333


In [113]:
print(x.min(axis=0)) # column wise operation - minimum in each column
print(x.max(axis=1)) # row wise operation - minimum in each row

[3 1 2]
[7 7 6]


In [114]:
print(x.std())
print(x.sum())

2.0
39


In [18]:
dir(x)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [19]:
help(x.argmax)

Help on built-in function argmax:

argmax(...) method of numpy.ndarray instance
    a.argmax(axis=None, out=None)
    
    Return indices of the maximum values along the given axis.
    
    Refer to `numpy.argmax` for full documentation.
    
    See Also
    --------
    numpy.argmax : equivalent function



In [20]:
x

array([[7, 1, 2],
       [3, 4, 7],
       [6, 5, 4]])

In [21]:
print(x[0:2,0:2])

[[7 1]
 [3 4]]


In [22]:
x[0,:] # to access the 0th row

array([7, 1, 2])

### Mathematical operations with numpy

In [115]:
np.mean(x)

4.333333333333333

In [116]:
np.median(x)

4.0

In [117]:
np.sin(np.deg2rad(90))

1.0

In [118]:
np.cos(np.deg2rad(90))

6.123233995736766e-17

In [119]:
np.exp(0.001)

1.0010005001667084

In [120]:
np.log10(10000)

4.0

In [121]:
np.std(x)

2.0

In [122]:
np.var(x)

4.0

### Creating arrays with numpy

In [123]:
# to create arrays with sequential values
x = np.arange(start=3,stop=20,step=2)
x

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [124]:
x = np.linspace(start=3,stop=20,num=9)
x

array([ 3.   ,  5.125,  7.25 ,  9.375, 11.5  , 13.625, 15.75 , 17.875,
       20.   ])

In [125]:
x = np.logspace(start=0,stop=5,num=6)
x

array([1.e+00, 1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05])

In [126]:
# creating an array with all values 0
x = np.zeros((4,3))
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [127]:
# creating an array with all values 1
x = np.ones((3,6))
x

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [128]:
x = 5*np.ones((3,6))
x

array([[5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5.]])

### Random data generation with numpy

In [133]:
# normaly distributed random numbers
x = np.random.randn(200)

In [134]:
x.mean()

0.06866919734943192

In [135]:
x.std()

0.9663210335993017

In [43]:
# uniform distribution b/w 0 to 1
x = np.random.rand(20)
x

array([0.8358224 , 0.21546587, 0.35440007, 0.66776706, 0.37720274,
       0.33044004, 0.32038671, 0.12926696, 0.92801499, 0.80545812,
       0.11412186, 0.53190207, 0.66606485, 0.32091418, 0.24814294,
       0.44685825, 0.09821947, 0.39950582, 0.72740889, 0.92439092])

In [44]:
# integer random numbers
x = np.random.randint(10,80,5)
x

array([25, 32, 66, 43, 63])

In [93]:
# integer random numbers
x = np.random.randint(10,80,(2,3))
x

array([[26, 15, 68],
       [10, 14, 46]])

In [95]:
y = np.matrix(x)
y

matrix([[26, 15, 68],
        [10, 14, 46]])

In [148]:
x1 = ['a','b','c','d','e','f','g','h']
x2 = [4,5,8,8,4,5,2,6,5,2]
y = np.random.choice(x1,4)
y

array(['g', 'c', 'e', 'b'], dtype='<U1')

In [183]:
np.random.seed(8)
# integer random numbers
x = np.random.randint(10,80,5)
x

array([77, 15, 18, 73, 58])

## Linear Algebra with numpy

In [184]:
x = np.matrix([[4,5,2],[7,4,1],[6,5,3]])
x

matrix([[4, 5, 2],
        [7, 4, 1],
        [6, 5, 3]])

In [185]:
np.linalg.det(x)

-24.999999999999996

In [186]:
np.linalg.inv(x)

matrix([[-2.80000000e-01,  2.00000000e-01,  1.20000000e-01],
        [ 6.00000000e-01, -4.09029535e-17, -4.00000000e-01],
        [-4.40000000e-01, -4.00000000e-01,  7.60000000e-01]])

In [187]:
np.linalg.eig(x)

(array([11.835432  , -1.92992898,  1.09449698]),
 matrix([[-0.51665639, -0.64758705,  0.02816612],
         [-0.5457641 ,  0.76183407, -0.38531021],
         [-0.65970275,  0.01548744,  0.92235715]]))

In [188]:
np.linalg.matrix_rank(x)

3

        4x - 5y = 10
        3x + y  = 17

In [189]:
a = [[4,-5],[3,1]] # creating a list of coefficients
b = [10,17] # a list of constants
np.linalg.solve(a,b) # to solve equations and get the values of x and y

array([5., 2.])